### ISSUE TITLE
working with SystemJS 0.18.x

### ISSUE THREAD

**Issue by wprater** [geelen/jspm-loader-css#16] opened 2015-08-11 01:49 UTC
I seem to be having issues with the plugin on SystemJS 0.18.x.  seems like it's trying to process it as JS and never gets to the `fetch` call.

**Comment by rbvea** [comment] 2015-08-16 21:22
:+1:

**Comment by gonzochic** [comment] 2015-08-19 15:37
same here

**Comment by chenxsan** [comment] 2015-08-20 04:57
I think this problem was caused by SystemJS [code change](https://github.com/systemjs/systemjs/commit/b9d5952c075fff4c2833d70c5c42021ee844d3b8#diff-9254b9e79d2209a77d013bf4df7e4810R97) here, @wprater 's commit https://github.com/geelen/jspm-loader-css/pull/18 could solve half the problem, the [path](https://github.com/geelen/jspm-loader-css/blob/master/index.js#L19) would still be a `undefined`. But we might extract it from `load.address`?

**Comment by chenxsan** [comment] 2015-08-20 06:04
Just created some demo codes [here](https://github.com/chenxsan/jspm-loader-css/commit/bc1657accab3c32644c8c013a955c3f5775e7e08) based on wprater's commit, works fine on my project as far as i can see.

**Comment by wprater** [comment] 2015-08-20 07:26
@chenxsan thanks, perhaps this is better. was this for an error with the builder?

**Comment by chenxsan** [comment] 2015-08-20 07:42
@wprater Oops, it would cause an error when building with jspm, guess there are better ways to do it.

**Comment by wprater** [comment] 2015-08-20 07:58
@chenxsan did you check my updated PR?

**Comment by chenxsan** [comment] 2015-08-20 08:03
@wprater Just checked it, it would export css class like "_http_127_0_0_1_9999_style_app__standout" if I had

```
:local(.standout) {} 
```

in my app.css file. That `_http_127_0_0_1_9999` part is needless.

**Comment by wprater** [comment] 2015-08-20 08:05
Ive never tried the modules feature.  is this another issue, or something related to the path still?  Im not sure I understand.

**Comment by chenxsan** [comment] 2015-08-20 08:16
If I had

```
:local(.standout){}
```

 in `style/app.css`, jspm-loader-css would produce a css class `._style_app__standout`, so your updated PR is ok, but that host part like `_http_127_0_0_1_9999` is redundant(I'm running the project in http://127.0.0.1:9999 with jspm-server), maybe @geelen can explain it better  :).

**Comment by f15gdsy** [comment] 2015-09-15 03:07
Hi, any updates on this issue?

**Comment by Hypercubed** [comment] 2015-09-15 05:25
@wprater Your patch-1 worked with `:local(.lol)` becoming `_http_localhost_8080_src_main__lol` but fails if I include `composes:` with the error `Uncaught (in promise) Error: Cannot read property 'push' of undefined(…)`.  Not sure if that is a separate issue.

**Comment by f15gdsy** [comment] 2015-09-16 02:35
Hi @wprater, I tried your fix, it works well using System.import. But when building using 'bundle-sfx', the css is not present in the code though classes are set correctly for html tag. I'm not sure why but do you have a fix for it? 
Thanks!

**Comment by f15gdsy** [comment] 2015-09-16 09:35
Based on @wprater 's pull request, I made it work in bundle mode too. Here is my [pull request](https://github.com/geelen/jspm-loader-css/pull/22).
It works for me when using 'bundle-sfx' to bundle the code.

**Comment by MeoMix** [comment] 2015-09-18 07:42
This still seems to be broken even with the PR? Is there something special that needs to happen?

**Comment by f15gdsy** [comment] 2015-09-18 09:20
@MeoMix which PR are you using? What's the error you got?

**Comment by MeoMix** [comment] 2015-09-18 18:36
@f15gdsy It seems to have fixed itself this morning after updating to the latest version of JSPM. Not sure if that's related at all, but I am successfully loading CSS now. :+1: 

EDIT:

Oh, it was because I was overriding css.js and didn't update that with the PR changes. I'm now doing:

```
import { CSSLoader, Plugins, fetch, bundle } from 'jspm-loader-css';

console.log('Plugins:', Plugins);

const loader = new CSSLoader([
    Plugins.autoprefixer()
], __moduleName);

export default loader;
export { CSSLoader, Plugins, fetch, bundle };
```

**Comment by geelen** [comment] 2015-09-21 14:25
Working on a new release to fix all these breakages. Will be a new major version, building on @douglasduteil's work. First PR merged in here: https://github.com/geelen/jspm-loader-css/pull/23

**Closed as completed by geelen** 2015-09-21 14:25 UTC
